# which go to the model you want to use
cfg_root: "/home/airl/workspace/OpenPCDet/tools/cfgs/kitti_models/pointpillar.yaml"

# which go to the .pth
model_path: "/home/airl/workspace/OpenPCDet/tools/pointpillar_7728.pth"

# pointcloud_topic in the bag if you are not sure
# rosbag info xxx.bag check the topic name
pointcloud_topic: "/velodyne_points" # default is from kitti2bag: /velodyne_points

# only the predict probablity over this threshold will be draw a box
threshold: 0.5

move_lidar_center: 20
viz_rate: 1.0
